{"name": "test_fail_password_empty[--对不起！请输入密码！]", "status": "passed", "attachments": [{"name": "stdout", "source": "48e63c07-4c9e-4c54-b822-e78e9a414548-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "''"}, {"name": "password", "value": "''"}, {"name": "expect", "value": "'对不起！请输入密码！'"}], "start": 1601430526996, "stop": 1601430533789, "uuid": "2338235c-221d-445b-8413-acd9d8768984", "historyId": "19c20d6591c707086577ec0f634f58fd", "testCaseId": "e048db9676071fc597e1087551b47302", "fullName": "TestCases.test_1_loginCase.TestLogin#test_fail_password_empty", "labels": [{"name": "tag", "value": "Test1"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_1_loginCase"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "HPTSJ003"}, {"name": "thread", "value": "19836-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_1_loginCase"}]}