{"name": "test_fail_password_empty[--对不起！请输入密码！]", "status": "passed", "attachments": [{"name": "stdout", "source": "6edb989f-964e-4088-802a-f2acaacede22-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "''"}, {"name": "password", "value": "''"}, {"name": "expect", "value": "'对不起！请输入密码！'"}], "start": 1601432212989, "stop": 1601432221796, "uuid": "a4d59fdd-afe1-47c0-b703-79b1d3fe9509", "historyId": "19c20d6591c707086577ec0f634f58fd", "testCaseId": "e048db9676071fc597e1087551b47302", "fullName": "TestCases.test_1_loginCase.TestLogin#test_fail_password_empty", "labels": [{"name": "tag", "value": "Test1"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_1_loginCase"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "HPTSJ003"}, {"name": "thread", "value": "21240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_1_loginCase"}]}